name: TabuuCore
version: 2020.1.0
main: nl.tabuu.tabuucore.TabuuCore
description: Tabuu's core plugin.
author: Tabuu
authors: [Tabuu]
website: http://www.tabuu.nl
softdepend: [PlaceholderAPI, Vault]
api-version: 1.15