name: TabuuCore
version: 2020.4.5
main: nl.tabuu.tabuucore.TabuuCore
description: Tabuu's core plugin.
author: Tabuu
authors: [Tabuu, CryptoMorin]
website: http://www.tabuu.nl
softdepend: [PlaceholderAPI, Vault]
api-version: 1.13